//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicksAutographsFormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NicksAutograph
    {
        public int AutographID { get; set; }
        public string CelebrityName { get; set; }
        public string Item { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateAquired { get; set; }
        public Nullable<decimal> AutographCost { get; set; }
        public Nullable<decimal> ItemCost { get; set; }
        public string ObtainedBy { get; set; }
        public string PictureLink { get; set; }
        public Nullable<System.DateTime> DateRecoreded { get; set; }
    }
}
